### ISSUE TITLE
Add gravity db location and docker functionality parameters 

### ISSUE THREAD

**Issue by BClev** [mmotti/PyPhDB#1]
To make this work on my Dockerized Pihole (stuck with Python 3.5 in the container), I ran this on the host and change the self.path_pihole.dir to the linked directory and changed the restart pihole function to do: 
`subprocess.call(['docker', 'exec', 'pihole', 'pihole', 'restartdns', 'reload'....` (with the first pihole being the container name).

Great script overall!

**Comment by mmotti** [comment]
Hi,

Thanks for your feedback!

Please see: https://github.com/mmotti/PyPhDB/commit/2d9beac1a569aace1f33911f08f6b9354e1ae2fb

~In summary, you should now be able to (hopefully) run the commands successfully by just appending `--docker` to the end of each one. This will set your directory to **./etc-pihole/** as per [here](https://hub.docker.com/r/pihole/pihole/) and prepend the subprocess command with `docker exec`. If you've chosen a different directory, you can also use the `--directory` switch to specify.~

~I haven't personally used docker before as I usually just use the standard installation, so I hope this covers everything.~

~Please see Readme for further info.~

~I'd appreciate it if you could let me know whether this works for you or not :-)~

Edit: Actually, doh! **./** will differ depending on the directory that you're in before the script is run. Are you able to let me know where docker creates the docker directory by default for Pi-hole?

**Comment by mmotti** [comment]
Sorry, another comment here.

After realising that the './' was subjective to your working directory before running the script, and being unsure of whether docker acts in the same way (which would make it difficult to determine where the directory is), I have changed it to require you to also specify the directory is you use the `--docker` flag.

So, to be clear, you have to append the commands with `--docker --directory '/your/pihole/volume'`

Edit: Will happily tweak if somebody can confirm whether docker saves the docker Pi-hole dir in the same location for everyone

**Comment by BClev** [comment]
@mmotti Worked perfectly! The directories are not in the same location on all installs (you decide when running the container or docker-compose), so this is great! Thanks!
