### ISSUE TITLE
Add comment to white/blacklist

### ISSUE THREAD

**Issue by hferreira23** [mmotti/PyPhDB#2]
First of all, thanks for this script. really useful.

Not really a bug more like a feature request.

When adding new domain to the white/black lists also add a comment so it appears on the GUI.

The following code does the trick.

`        dict_sql = {
            'adlists.list':
            'INSERT OR IGNORE INTO adlist (address) VALUES (?)\
            |DELETE FROM adlist WHERE address IN (?)',
            'whitelist.list':
            'INSERT OR IGNORE INTO domainlist (type, domain, enabled, comment) VALUES (0, ?, 1, "Imported by PyPhDB")\
            |DELETE FROM domainlist WHERE domain IN (?) AND type = 0\
            |DELETE FROM domainlist WHERE type = 0',
            'blacklist.list':
            'INSERT OR IGNORE INTO domainlist (type, domain, enabled, comment) VALUES (1, ?, 1, "Imported by PyPhDB")\
            |DELETE FROM domainlist WHERE domain IN (?) AND type = 1\
            |DELETE FROM domainlist WHERE type = 1',
            'whitelist_regex.list':
            'INSERT OR IGNORE INTO domainlist (type, domain, enabled, comment) VALUES (2, ?, 1, "Imported by PyPhDB")\
            |DELETE FROM domainlist WHERE domain IN (?) AND type = 2\
            |DELETE FROM domainlist WHERE type = 2',
            'regex.list':
            'INSERT OR IGNORE INTO domainlist (type, domain, enabled, comment) VALUES (3, ?, 1, "Imported by PyPhDB")\
            |DELETE FROM domainlist WHERE domain IN (?) AND type = 3\
            |DELETE FROM domainlist WHERE type = 3'`

Happy to open a MR if you want.

Cheers

**Comment by mmotti** [comment]
Hey!

Thanks for your suggestion.

I will look at this; I have done something similar with the adding my
regexps but didn't think to do it for this.

I need to have a bit of a think about whether there's a better way to store
the queries as it's a bit messy at the moment.

**Comment by mmotti** [comment]
Added in https://github.com/mmotti/PyPhDB/commit/64b13c364bcc643e2faea0f38e138b1d2d9c43dd

Comment stored in `self.comment` and fed to the executemany command in `self.cursor.executemany(dict_sql[k].split('|')[0], [(x, self.comment) for x in set_modified])`

Essentially the same as how you listed above, just saves repeating the same comment over and over in the code :-)
